# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e651403804254c331420055ae7db07c3848da8e84afd9f681bee873533ffdde65ac4f3039339a1292c8c537f49c1bed2e097943755cc5e9e83c87f2562bc2f

test:
  secret_key_base: e44f55dc9f837702569883282614fb1f4f5c076f450afe8f1e601efa2feaa01aa85ae3420c494f9477a1bb1f5c2bbcb42120066f3073649872db86e500cc34ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
